// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserProtos.proto

package pl.stormit.protobuf;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:stormit.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string surname = 2;</code>
     */
    boolean hasSurname();
    /**
     * <code>optional string surname = 2;</code>
     */
    java.lang.String getSurname();
    /**
     * <code>optional string surname = 2;</code>
     */
    com.google.protobuf.ByteString
        getSurnameBytes();

    /**
     * <code>required int32 age = 3;</code>
     */
    boolean hasAge();
    /**
     * <code>required int32 age = 3;</code>
     */
    int getAge();

    /**
     * <code>repeated .stormit.User.Interest interests = 4;</code>
     */
    java.util.List<pl.stormit.protobuf.UserProtos.User.Interest> 
        getInterestsList();
    /**
     * <code>repeated .stormit.User.Interest interests = 4;</code>
     */
    pl.stormit.protobuf.UserProtos.User.Interest getInterests(int index);
    /**
     * <code>repeated .stormit.User.Interest interests = 4;</code>
     */
    int getInterestsCount();
    /**
     * <code>repeated .stormit.User.Interest interests = 4;</code>
     */
    java.util.List<? extends pl.stormit.protobuf.UserProtos.User.InterestOrBuilder> 
        getInterestsOrBuilderList();
    /**
     * <code>repeated .stormit.User.Interest interests = 4;</code>
     */
    pl.stormit.protobuf.UserProtos.User.InterestOrBuilder getInterestsOrBuilder(
        int index);

    /**
     * <code>required .stormit.User.UserType userType = 5;</code>
     */
    boolean hasUserType();
    /**
     * <code>required .stormit.User.UserType userType = 5;</code>
     */
    pl.stormit.protobuf.UserProtos.User.UserType getUserType();
  }
  /**
   * Protobuf type {@code stormit.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:stormit.User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      surname_ = "";
      age_ = 0;
      interests_ = java.util.Collections.emptyList();
      userType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              surname_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              age_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                interests_ = new java.util.ArrayList<pl.stormit.protobuf.UserProtos.User.Interest>();
                mutable_bitField0_ |= 0x00000008;
              }
              interests_.add(
                  input.readMessage(pl.stormit.protobuf.UserProtos.User.Interest.PARSER, extensionRegistry));
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              pl.stormit.protobuf.UserProtos.User.UserType value = pl.stormit.protobuf.UserProtos.User.UserType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                userType_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          interests_ = java.util.Collections.unmodifiableList(interests_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.stormit.protobuf.UserProtos.internal_static_stormit_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.stormit.protobuf.UserProtos.internal_static_stormit_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.stormit.protobuf.UserProtos.User.class, pl.stormit.protobuf.UserProtos.User.Builder.class);
    }

    /**
     * Protobuf enum {@code stormit.User.UserType}
     */
    public enum UserType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NORMAL = 0;</code>
       */
      NORMAL(0),
      /**
       * <code>ADMIN = 1;</code>
       */
      ADMIN(1),
      ;

      /**
       * <code>NORMAL = 0;</code>
       */
      public static final int NORMAL_VALUE = 0;
      /**
       * <code>ADMIN = 1;</code>
       */
      public static final int ADMIN_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static UserType valueOf(int value) {
        return forNumber(value);
      }

      public static UserType forNumber(int value) {
        switch (value) {
          case 0: return NORMAL;
          case 1: return ADMIN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<UserType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          UserType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
              public UserType findValueByNumber(int number) {
                return UserType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pl.stormit.protobuf.UserProtos.User.getDescriptor().getEnumTypes().get(0);
      }

      private static final UserType[] VALUES = values();

      public static UserType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private UserType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:stormit.User.UserType)
    }

    public interface InterestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:stormit.User.Interest)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code stormit.User.Interest}
     */
    public  static final class Interest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:stormit.User.Interest)
        InterestOrBuilder {
      // Use Interest.newBuilder() to construct.
      private Interest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Interest() {
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Interest(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                name_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.stormit.protobuf.UserProtos.internal_static_stormit_User_Interest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.stormit.protobuf.UserProtos.internal_static_stormit_User_Interest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.stormit.protobuf.UserProtos.User.Interest.class, pl.stormit.protobuf.UserProtos.User.Interest.Builder.class);
      }

      private int bitField0_;
      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof pl.stormit.protobuf.UserProtos.User.Interest)) {
          return super.equals(obj);
        }
        pl.stormit.protobuf.UserProtos.User.Interest other = (pl.stormit.protobuf.UserProtos.User.Interest) obj;

        boolean result = true;
        result = result && (hasName() == other.hasName());
        if (hasName()) {
          result = result && getName()
              .equals(other.getName());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (hasName()) {
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static pl.stormit.protobuf.UserProtos.User.Interest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pl.stormit.protobuf.UserProtos.User.Interest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pl.stormit.protobuf.UserProtos.User.Interest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pl.stormit.protobuf.UserProtos.User.Interest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pl.stormit.protobuf.UserProtos.User.Interest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static pl.stormit.protobuf.UserProtos.User.Interest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static pl.stormit.protobuf.UserProtos.User.Interest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static pl.stormit.protobuf.UserProtos.User.Interest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static pl.stormit.protobuf.UserProtos.User.Interest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static pl.stormit.protobuf.UserProtos.User.Interest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(pl.stormit.protobuf.UserProtos.User.Interest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code stormit.User.Interest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:stormit.User.Interest)
          pl.stormit.protobuf.UserProtos.User.InterestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return pl.stormit.protobuf.UserProtos.internal_static_stormit_User_Interest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return pl.stormit.protobuf.UserProtos.internal_static_stormit_User_Interest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  pl.stormit.protobuf.UserProtos.User.Interest.class, pl.stormit.protobuf.UserProtos.User.Interest.Builder.class);
        }

        // Construct using pl.stormit.protobuf.UserProtos.User.Interest.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return pl.stormit.protobuf.UserProtos.internal_static_stormit_User_Interest_descriptor;
        }

        public pl.stormit.protobuf.UserProtos.User.Interest getDefaultInstanceForType() {
          return pl.stormit.protobuf.UserProtos.User.Interest.getDefaultInstance();
        }

        public pl.stormit.protobuf.UserProtos.User.Interest build() {
          pl.stormit.protobuf.UserProtos.User.Interest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public pl.stormit.protobuf.UserProtos.User.Interest buildPartial() {
          pl.stormit.protobuf.UserProtos.User.Interest result = new pl.stormit.protobuf.UserProtos.User.Interest(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof pl.stormit.protobuf.UserProtos.User.Interest) {
            return mergeFrom((pl.stormit.protobuf.UserProtos.User.Interest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(pl.stormit.protobuf.UserProtos.User.Interest other) {
          if (other == pl.stormit.protobuf.UserProtos.User.Interest.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          pl.stormit.protobuf.UserProtos.User.Interest parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (pl.stormit.protobuf.UserProtos.User.Interest) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              name_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:stormit.User.Interest)
      }

      // @@protoc_insertion_point(class_scope:stormit.User.Interest)
      private static final pl.stormit.protobuf.UserProtos.User.Interest DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new pl.stormit.protobuf.UserProtos.User.Interest();
      }

      public static pl.stormit.protobuf.UserProtos.User.Interest getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Interest>
          PARSER = new com.google.protobuf.AbstractParser<Interest>() {
        public Interest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Interest(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Interest> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Interest> getParserForType() {
        return PARSER;
      }

      public pl.stormit.protobuf.UserProtos.User.Interest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SURNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object surname_;
    /**
     * <code>optional string surname = 2;</code>
     */
    public boolean hasSurname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string surname = 2;</code>
     */
    public java.lang.String getSurname() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          surname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string surname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSurnameBytes() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        surname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>required int32 age = 3;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int INTERESTS_FIELD_NUMBER = 4;
    private java.util.List<pl.stormit.protobuf.UserProtos.User.Interest> interests_;
    /**
     * <code>repeated .stormit.User.Interest interests = 4;</code>
     */
    public java.util.List<pl.stormit.protobuf.UserProtos.User.Interest> getInterestsList() {
      return interests_;
    }
    /**
     * <code>repeated .stormit.User.Interest interests = 4;</code>
     */
    public java.util.List<? extends pl.stormit.protobuf.UserProtos.User.InterestOrBuilder> 
        getInterestsOrBuilderList() {
      return interests_;
    }
    /**
     * <code>repeated .stormit.User.Interest interests = 4;</code>
     */
    public int getInterestsCount() {
      return interests_.size();
    }
    /**
     * <code>repeated .stormit.User.Interest interests = 4;</code>
     */
    public pl.stormit.protobuf.UserProtos.User.Interest getInterests(int index) {
      return interests_.get(index);
    }
    /**
     * <code>repeated .stormit.User.Interest interests = 4;</code>
     */
    public pl.stormit.protobuf.UserProtos.User.InterestOrBuilder getInterestsOrBuilder(
        int index) {
      return interests_.get(index);
    }

    public static final int USERTYPE_FIELD_NUMBER = 5;
    private int userType_;
    /**
     * <code>required .stormit.User.UserType userType = 5;</code>
     */
    public boolean hasUserType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .stormit.User.UserType userType = 5;</code>
     */
    public pl.stormit.protobuf.UserProtos.User.UserType getUserType() {
      pl.stormit.protobuf.UserProtos.User.UserType result = pl.stormit.protobuf.UserProtos.User.UserType.valueOf(userType_);
      return result == null ? pl.stormit.protobuf.UserProtos.User.UserType.NORMAL : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getInterestsCount(); i++) {
        if (!getInterests(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, surname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, age_);
      }
      for (int i = 0; i < interests_.size(); i++) {
        output.writeMessage(4, interests_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(5, userType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, surname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      for (int i = 0; i < interests_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, interests_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, userType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pl.stormit.protobuf.UserProtos.User)) {
        return super.equals(obj);
      }
      pl.stormit.protobuf.UserProtos.User other = (pl.stormit.protobuf.UserProtos.User) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasSurname() == other.hasSurname());
      if (hasSurname()) {
        result = result && getSurname()
            .equals(other.getSurname());
      }
      result = result && (hasAge() == other.hasAge());
      if (hasAge()) {
        result = result && (getAge()
            == other.getAge());
      }
      result = result && getInterestsList()
          .equals(other.getInterestsList());
      result = result && (hasUserType() == other.hasUserType());
      if (hasUserType()) {
        result = result && userType_ == other.userType_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasSurname()) {
        hash = (37 * hash) + SURNAME_FIELD_NUMBER;
        hash = (53 * hash) + getSurname().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (getInterestsCount() > 0) {
        hash = (37 * hash) + INTERESTS_FIELD_NUMBER;
        hash = (53 * hash) + getInterestsList().hashCode();
      }
      if (hasUserType()) {
        hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
        hash = (53 * hash) + userType_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pl.stormit.protobuf.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.stormit.protobuf.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.stormit.protobuf.UserProtos.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.stormit.protobuf.UserProtos.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.stormit.protobuf.UserProtos.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.stormit.protobuf.UserProtos.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.stormit.protobuf.UserProtos.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pl.stormit.protobuf.UserProtos.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.stormit.protobuf.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.stormit.protobuf.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pl.stormit.protobuf.UserProtos.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code stormit.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:stormit.User)
        pl.stormit.protobuf.UserProtos.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.stormit.protobuf.UserProtos.internal_static_stormit_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.stormit.protobuf.UserProtos.internal_static_stormit_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.stormit.protobuf.UserProtos.User.class, pl.stormit.protobuf.UserProtos.User.Builder.class);
      }

      // Construct using pl.stormit.protobuf.UserProtos.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInterestsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        surname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (interestsBuilder_ == null) {
          interests_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          interestsBuilder_.clear();
        }
        userType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.stormit.protobuf.UserProtos.internal_static_stormit_User_descriptor;
      }

      public pl.stormit.protobuf.UserProtos.User getDefaultInstanceForType() {
        return pl.stormit.protobuf.UserProtos.User.getDefaultInstance();
      }

      public pl.stormit.protobuf.UserProtos.User build() {
        pl.stormit.protobuf.UserProtos.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.stormit.protobuf.UserProtos.User buildPartial() {
        pl.stormit.protobuf.UserProtos.User result = new pl.stormit.protobuf.UserProtos.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.surname_ = surname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.age_ = age_;
        if (interestsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            interests_ = java.util.Collections.unmodifiableList(interests_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.interests_ = interests_;
        } else {
          result.interests_ = interestsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userType_ = userType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.stormit.protobuf.UserProtos.User) {
          return mergeFrom((pl.stormit.protobuf.UserProtos.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.stormit.protobuf.UserProtos.User other) {
        if (other == pl.stormit.protobuf.UserProtos.User.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSurname()) {
          bitField0_ |= 0x00000002;
          surname_ = other.surname_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (interestsBuilder_ == null) {
          if (!other.interests_.isEmpty()) {
            if (interests_.isEmpty()) {
              interests_ = other.interests_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureInterestsIsMutable();
              interests_.addAll(other.interests_);
            }
            onChanged();
          }
        } else {
          if (!other.interests_.isEmpty()) {
            if (interestsBuilder_.isEmpty()) {
              interestsBuilder_.dispose();
              interestsBuilder_ = null;
              interests_ = other.interests_;
              bitField0_ = (bitField0_ & ~0x00000008);
              interestsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInterestsFieldBuilder() : null;
            } else {
              interestsBuilder_.addAllMessages(other.interests_);
            }
          }
        }
        if (other.hasUserType()) {
          setUserType(other.getUserType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasAge()) {
          return false;
        }
        if (!hasUserType()) {
          return false;
        }
        for (int i = 0; i < getInterestsCount(); i++) {
          if (!getInterests(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.stormit.protobuf.UserProtos.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.stormit.protobuf.UserProtos.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object surname_ = "";
      /**
       * <code>optional string surname = 2;</code>
       */
      public boolean hasSurname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string surname = 2;</code>
       */
      public java.lang.String getSurname() {
        java.lang.Object ref = surname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            surname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string surname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSurnameBytes() {
        java.lang.Object ref = surname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          surname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string surname = 2;</code>
       */
      public Builder setSurname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        surname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string surname = 2;</code>
       */
      public Builder clearSurname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        surname_ = getDefaultInstance().getSurname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string surname = 2;</code>
       */
      public Builder setSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        surname_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>required int32 age = 3;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>required int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000004;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 age = 3;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<pl.stormit.protobuf.UserProtos.User.Interest> interests_ =
        java.util.Collections.emptyList();
      private void ensureInterestsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          interests_ = new java.util.ArrayList<pl.stormit.protobuf.UserProtos.User.Interest>(interests_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          pl.stormit.protobuf.UserProtos.User.Interest, pl.stormit.protobuf.UserProtos.User.Interest.Builder, pl.stormit.protobuf.UserProtos.User.InterestOrBuilder> interestsBuilder_;

      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public java.util.List<pl.stormit.protobuf.UserProtos.User.Interest> getInterestsList() {
        if (interestsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(interests_);
        } else {
          return interestsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public int getInterestsCount() {
        if (interestsBuilder_ == null) {
          return interests_.size();
        } else {
          return interestsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public pl.stormit.protobuf.UserProtos.User.Interest getInterests(int index) {
        if (interestsBuilder_ == null) {
          return interests_.get(index);
        } else {
          return interestsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public Builder setInterests(
          int index, pl.stormit.protobuf.UserProtos.User.Interest value) {
        if (interestsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInterestsIsMutable();
          interests_.set(index, value);
          onChanged();
        } else {
          interestsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public Builder setInterests(
          int index, pl.stormit.protobuf.UserProtos.User.Interest.Builder builderForValue) {
        if (interestsBuilder_ == null) {
          ensureInterestsIsMutable();
          interests_.set(index, builderForValue.build());
          onChanged();
        } else {
          interestsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public Builder addInterests(pl.stormit.protobuf.UserProtos.User.Interest value) {
        if (interestsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInterestsIsMutable();
          interests_.add(value);
          onChanged();
        } else {
          interestsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public Builder addInterests(
          int index, pl.stormit.protobuf.UserProtos.User.Interest value) {
        if (interestsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInterestsIsMutable();
          interests_.add(index, value);
          onChanged();
        } else {
          interestsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public Builder addInterests(
          pl.stormit.protobuf.UserProtos.User.Interest.Builder builderForValue) {
        if (interestsBuilder_ == null) {
          ensureInterestsIsMutable();
          interests_.add(builderForValue.build());
          onChanged();
        } else {
          interestsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public Builder addInterests(
          int index, pl.stormit.protobuf.UserProtos.User.Interest.Builder builderForValue) {
        if (interestsBuilder_ == null) {
          ensureInterestsIsMutable();
          interests_.add(index, builderForValue.build());
          onChanged();
        } else {
          interestsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public Builder addAllInterests(
          java.lang.Iterable<? extends pl.stormit.protobuf.UserProtos.User.Interest> values) {
        if (interestsBuilder_ == null) {
          ensureInterestsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, interests_);
          onChanged();
        } else {
          interestsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public Builder clearInterests() {
        if (interestsBuilder_ == null) {
          interests_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          interestsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public Builder removeInterests(int index) {
        if (interestsBuilder_ == null) {
          ensureInterestsIsMutable();
          interests_.remove(index);
          onChanged();
        } else {
          interestsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public pl.stormit.protobuf.UserProtos.User.Interest.Builder getInterestsBuilder(
          int index) {
        return getInterestsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public pl.stormit.protobuf.UserProtos.User.InterestOrBuilder getInterestsOrBuilder(
          int index) {
        if (interestsBuilder_ == null) {
          return interests_.get(index);  } else {
          return interestsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public java.util.List<? extends pl.stormit.protobuf.UserProtos.User.InterestOrBuilder> 
           getInterestsOrBuilderList() {
        if (interestsBuilder_ != null) {
          return interestsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(interests_);
        }
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public pl.stormit.protobuf.UserProtos.User.Interest.Builder addInterestsBuilder() {
        return getInterestsFieldBuilder().addBuilder(
            pl.stormit.protobuf.UserProtos.User.Interest.getDefaultInstance());
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public pl.stormit.protobuf.UserProtos.User.Interest.Builder addInterestsBuilder(
          int index) {
        return getInterestsFieldBuilder().addBuilder(
            index, pl.stormit.protobuf.UserProtos.User.Interest.getDefaultInstance());
      }
      /**
       * <code>repeated .stormit.User.Interest interests = 4;</code>
       */
      public java.util.List<pl.stormit.protobuf.UserProtos.User.Interest.Builder> 
           getInterestsBuilderList() {
        return getInterestsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          pl.stormit.protobuf.UserProtos.User.Interest, pl.stormit.protobuf.UserProtos.User.Interest.Builder, pl.stormit.protobuf.UserProtos.User.InterestOrBuilder> 
          getInterestsFieldBuilder() {
        if (interestsBuilder_ == null) {
          interestsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              pl.stormit.protobuf.UserProtos.User.Interest, pl.stormit.protobuf.UserProtos.User.Interest.Builder, pl.stormit.protobuf.UserProtos.User.InterestOrBuilder>(
                  interests_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          interests_ = null;
        }
        return interestsBuilder_;
      }

      private int userType_ = 0;
      /**
       * <code>required .stormit.User.UserType userType = 5;</code>
       */
      public boolean hasUserType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .stormit.User.UserType userType = 5;</code>
       */
      public pl.stormit.protobuf.UserProtos.User.UserType getUserType() {
        pl.stormit.protobuf.UserProtos.User.UserType result = pl.stormit.protobuf.UserProtos.User.UserType.valueOf(userType_);
        return result == null ? pl.stormit.protobuf.UserProtos.User.UserType.NORMAL : result;
      }
      /**
       * <code>required .stormit.User.UserType userType = 5;</code>
       */
      public Builder setUserType(pl.stormit.protobuf.UserProtos.User.UserType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        userType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .stormit.User.UserType userType = 5;</code>
       */
      public Builder clearUserType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:stormit.User)
    }

    // @@protoc_insertion_point(class_scope:stormit.User)
    private static final pl.stormit.protobuf.UserProtos.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pl.stormit.protobuf.UserProtos.User();
    }

    public static pl.stormit.protobuf.UserProtos.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public pl.stormit.protobuf.UserProtos.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stormit_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stormit_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stormit_User_Interest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stormit_User_Interest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020UserProtos.proto\022\007stormit\"\304\001\n\004User\022\014\n\004" +
      "name\030\001 \002(\t\022\017\n\007surname\030\002 \001(\t\022\013\n\003age\030\003 \002(\005" +
      "\022)\n\tinterests\030\004 \003(\0132\026.stormit.User.Inter" +
      "est\022(\n\010userType\030\005 \002(\0162\026.stormit.User.Use" +
      "rType\032\030\n\010Interest\022\014\n\004name\030\001 \002(\t\"!\n\010UserT" +
      "ype\022\n\n\006NORMAL\020\000\022\t\n\005ADMIN\020\001B!\n\023pl.stormit" +
      ".protobufB\nUserProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_stormit_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stormit_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stormit_User_descriptor,
        new java.lang.String[] { "Name", "Surname", "Age", "Interests", "UserType", });
    internal_static_stormit_User_Interest_descriptor =
      internal_static_stormit_User_descriptor.getNestedTypes().get(0);
    internal_static_stormit_User_Interest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stormit_User_Interest_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
